### PR TITLE
Set One & Two

### PR DESCRIPTION
**Pull request by ramenhog**

### CODE REVIEW

**Comment by jztaddwater** [comment]
Set Two

**Comment by ramenhog** [comment]
@EliseWei A few questions :)

using setTimeout, run setStyles on the box once every second, continuously. Ok, then turn it off.
- for the "turning it off" part, is it just turning it off via inspector?

create a new loop that smoothly animates the position of the box, moving it 60 times per second. 1px horizontal and 1px vertical is a good velocity to start.
- is it moving it from it's previous position to the new position that's generated by `setStyles`?
- no CSS right? :sob:

**Comment by EliseWei** [comment]
For turning off the timeout loop, you can comment it out, delete it, or use it to build the next item. The purpose is to build a self-calling timeout loop and see it visibly working.

For the animation, you'll use another timeout loop (running 60x faster) to modify the top and left properties 1px at a time. You won't need setStyles at all, in that loop; it will just be used for initializing the divs.

**Comment by EliseWei** [comment]
Please open a new PR for just Set 1 against origin branch stephanie_l (not master). I can merge that in, and then open another PR for just Set 2 changes.

**Pull request closed without merging**
